import rclpy
from rclpy.node import Node
from std_msgs.msg import String
import json
import logging

# This node acts as the main orchestrator for the capstone project.
# It subscribes to the action sequences generated by the cognitive planner
# and (conceptually) dispatches them to specialized robot control interfaces
# (e.g., Nav2 action client, manipulation controller).

class CapstoneOrchestrator(Node):
    def __init__(self):
        super().__init__('capstone_orchestrator')
        self.action_sequence_subscription = self.create_subscription(
            String,
            '/robot_action_sequence',
            self.orchestrate_actions_callback,
            10
        )
        self.get_logger().info('Capstone Orchestrator node started. Waiting for action sequences.')

    def orchestrate_actions_callback(self, msg):
        try:
            action_sequence = json.loads(msg.data)
            self.get_logger().info(f"Received action sequence for orchestration: {action_sequence}")

            for action in action_sequence:
                action_type = action.get('action')
                params = action.get('params', {})
                self.get_logger().info(f"Orchestrating action: {action_type} with params: {params}")

                # In a full implementation, this would involve calling
                # ROS 2 action clients, service clients, or publishing messages
                # to trigger navigation, perception, or manipulation.
                
                if action_type == 'navigate_to_pose':
                    self.get_logger().info(f" -> Dispatching navigation to ({params.get('x')}, {params.get('y')})")
                elif action_type == 'pick_up_object':
                    self.get_logger().info(f" -> Dispatching manipulation for {params.get('object_name')}")
                elif action_type == 'find_object':
                    self.get_logger().info(f" -> Dispatching perception to find {params.get('object_name')}")
                elif action_type == 'say_phrase':
                    self.get_logger().info(f" -> Dispatching TTS for phrase: {params.get('phrase')}")
                else:
                    self.get_logger().warn(f"Unknown action type in sequence: {action_type}")
                
                # Simulate action execution time
                self.get_logger().info(f"Simulating execution of {action_type}...")
                rclpy.spin_once(self, timeout_sec=2) # Simulate blocking call

            self.get_logger().info("Action sequence orchestrated successfully.")

        except json.JSONDecodeError as e:
            self.get_logger().error(f"Failed to parse action sequence JSON: {e}")
        except Exception as e:
            self.get_logger().error(f"Error during action orchestration: {e}")

def main(args=None):
    logging.basicConfig(level=logging.INFO)
    rclpy.init(args=args)
    orchestrator = CapstoneOrchestrator()
    rclpy.spin(orchestrator)
    orchestrator.destroy_node()
    rclpy.shutdown()

if __name__ == '__main__':
    main()
